[package]
name = "project1"
version = "0.1.0"
authors = ["tonimakkonen <toni.a.makkonen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.4"
gl = "0.14.0"
